# config.yml
version: 1.0.0
chains:
  core:
    rpc_url: "https://rpc.coredao.org"
    scan_url: "https://scan.coredao.org"
    token_name: "CORE"
    usdt_contract: "0x3c4b1f8d2e5c6b7f9a1d8c3e4b5f6a7b8c9d0e1f"
    usdc_contract: "0x2b2e4f8c5d6a7b8c9d0e1f2a3b4c5d6e7f8g9h0i"
  bsc:
    rpc_url: "https://bsc-dataseed.binance.org/"
    scan_url: "https://bscscan.com"
    token_name: "BNB"
    usdt_contract: "0x55d398326f99059fF775485246999027B3197955"
    usdc_contract: "0x8ac76a51cc950d9822d68b83fE1Ad97B32Cd580d"

active_chain: "bsc"
